<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>Modul Ajar - {{ $module->title }}</title>
    <style>
        body {
            font-family: 'Helvetica', 'Arial', sans-serif;
            line-height: 1.6;
            color: #333;
            padding: 20px;
        }
        .header {
            text-align: center;
            border-bottom: 2px solid #4f46e5;
            margin-bottom: 30px;
            padding-bottom: 10px;
        }
        .header h1 {
            margin: 0;
            color: #4f46e5;
            font-size: 24px;
        }
        .header p {
            margin: 5px 0 0;
            color: #6b7280;
            font-size: 14px;
        }
        .meta {
            margin-bottom: 30px;
            background: #f9fafb;
            padding: 15px;
            border-radius: 8px;
        }
        .meta-grid {
            width: 100%;
        }
        .meta-grid td {
            padding: 5px 0;
            font-size: 13px;
        }
        .meta-label {
            font-weight: bold;
            width: 150px;
        }
        .content {
            font-size: 14px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin: 15px 0;
        }
        th, td {
            border: 1px solid #e5e7eb;
            padding: 10px;
            text-align: left;
        }
        th {
            background-color: #f3f4f6;
        }
        .footer {
            margin-top: 50px;
            font-size: 10px;
            text-align: center;
            color: #9ca3af;
            border-top: 1px solid #e5e7eb;
            padding-top: 10px;
        }
        /* Markdown Style Emulation */
        h1, h2, h3 { color: #1e293b; }
        h1 { font-size: 20px; border-bottom: 1px solid #e5e7eb; padding-bottom: 5px; }
        h2 { font-size: 18px; margin-top: 20px; }
        h3 { font-size: 16px; }
        ul, ol { padding-left: 20px; }
    </style>
</head>
<body>
    <div class="header">
        <h1>MODUL AJAR KURIKULUM MERDEKA</h1>
        <p>Generated by SIUBA AI Assistant</p>
    </div>

    <div class="meta">
        <table class="meta-grid">
            <tr>
                <td class="meta-label">Judul / Tema:</td>
                <td>{{ $module->title }}</td>
                <td class="meta-label">Penyusun:</td>
                <td>{{ $module->user->name }}</td>
            </tr>
            <tr>
                <td class="meta-label">Mata Pelajaran:</td>
                <td>{{ $module->subject }}</td>
                <td class="meta-label">Tanggal:</td>
                <td>{{ $module->created_at->format('d F Y') }}</td>
            </tr>
            <tr>
                <td class="meta-label">Kelas / Jenjang:</td>
                <td>{{ $module->class_level }}</td>
                <td class="meta-label">Satuan Pendidikan:</td>
                <td>SIUBA</td>
            </tr>
        </table>
    </div>

    <div class="content">
        {!! \Illuminate\Support\Str::markdown($module->generated_content) !!}
    </div>

    <div class="footer">
        Dokumen ini dibuat secara otomatis menggunakan bantuan AI melalui platform SIUBA.
    </div>
</body>
</html>
